### ISSUE TITLE
Extra parameters in setup command has wrong error message

### ISSUE THREAD

**Issue by Yongbeom-Kim** [Yongbeom-Kim/pe#4]
When `setup g/m a/20 w/70 i/70 h/175 q/54321` is input, the following message appears:

![image.png](https://raw.githubusercontent.com/Yongbeom-Kim/pe/main/files/b2cdff87-7047-456d-a92a-6865e86bc992.png)

Similar iterations of the message appear when the erroneous parameter is in different positions:

![image.png](https://raw.githubusercontent.com/Yongbeom-Kim/pe/main/files/a37be432-872d-440b-ba59-dbf54edee205.png)

![image.png](https://raw.githubusercontent.com/Yongbeom-Kim/pe/main/files/6cdf8424-f17b-49f8-9e05-ccc32176c5f4.png)

Considered a low severity bug.

**Comment by nus-se-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
This is the intended behaviour of our app. For example when giving  "setup g/m q/54321 a/20 w/70 i/70 h/175"  as a command, the "q/54321" portion is read together with "m" as a parameter called "m q/54321". Since it does not pass the input validation of being either "M" or "F", this results in the following error message being thrown: "Gender must be a single char, either M or F", which is the intended behaviour.

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------
